### ISSUE TITLE
`gulp --production` report error: assets/js/app.min.js: Unexpected character '`'

### ISSUE THREAD

**Issue by wensonsmith** [zietbukuel/oktober-foundation#1]
It's seems gulp-uglify can't recognize string templates,  But i don't known how to solve it

**Comment by zietbukuel** [comment]
Can you please let me know how can I reproduce this? Thanks.

**Comment by wensonsmith** [comment]
1)  If install this theme from october backend , it will miss the `.bowerrc` file . so bower install can't install plugins to vendor folder. it will report errors;  so i git clone , then `npm install && bower install` . 

After that , run `gulp` works fine . But `gulp --production` still report error . so..next

2)   For debugger this error , run  `npm install gulp-util ` to install the plugin. then edit gulpfile.js,
add this to line 23:

```js
gutil = require('gulp-util'),
```
then change 

```js
.pipe( gulpif(args.production, uglify( { preserveComments: "license" } ) ) )
```

to

```js
.pipe( gulpif(args.production, uglify( { preserveComments: "license" }).on('error', gutil.log) ) )
```

run `gulp --production` , it will show the error .

**Comment by zietbukuel** [comment]
This bug has been fixed in the new release, please check it out.
