### ISSUE TITLE
Foundation bower components failing in Safari

### ISSUE THREAD

**Issue by CobraClutch** [zietbukuel/oktober-foundation#2]
Thanks for this great starter theme. Please bear with me, as I'm still learning all the different aspects of bower, gulp, October, etc...

When I compile the default app.js in my theme, it throws all sorts of javascript errors in Safari. But if I remove all the references to **_//= require ../../bower_components/foundation-sites/js/_** and replace it with **_//= require ../../bower_components/foundation-sites/dist/foundation.js_**, it loads error-free.

Why are the individual /foundation-sites/js components different from the full distribution version? Is there something I need to change in my gulpfile? Sorry if this is a question better suited for the Foundation community.

Thanks!

**Comment by zietbukuel** [comment]
Can you please paste the errors you're getting? Also, I've updated the theme recently to fix some of these errors, have you tried the updated version? Thanks.

**Comment by CobraClutch** [comment]
Yes, I'm using the latest version of the theme.

With the default individual bower component paths in es6/app.js, this is an error I get in Safari:
**_SyntaxError: Unexpected token '='. Expected a ')' or a ',' after a parameter declaration._**

This happens at the first line inside the Abide class (constructor(element, options = {}).

If I get rid of all the individual foundation-sites bower components and just load the distribution foundation.js (from bower), everything works just fine.

**Comment by zietbukuel** [comment]
I see what's going on. You shouldn't be including this file into your website. The `assets/es6/app.js` file only contains your includes and custom code. 

Your custom JS should be inside this block:

```javascript
/* Theme Javascript */
jQuery(document).ready(function($){

 YOUR CUSTOM CODE HERE

});
```

After compiling using `gulp` you should include `assets/js/app.js` or `assets/js/app.min.js` (minified) in your HTML.

You get app.js simply by running `gulp` and you get app.min.js running `gulp --production`.

**Comment by CobraClutch** [comment]
Yes, I'm referencing the compiled `assets/js/app.js`. I don't include the es6/app.js directly.

**Comment by zietbukuel** [comment]
I'll do some tests tonight to see if I get the same errors on Safari then.

**Comment by CobraClutch** [comment]
I've attached two files. `app-original.js` is the one from this repo that (when compiled), throws errors in Safari. `app-working.js` is what I use to get an error-free javascript file.

It's not a big deal, it would just be nice to cherry-pick the scripts. Thanks!

[js.zip](https://github.com/zietbukuel/oktober-foundation/files/409751/js.zip)

**Comment by zietbukuel** [comment]
I've updated the theme with the lates Foundation. This should fix the issues you were having. If not please let me know. Sorry for the huge delay, I've been really busy.
