### ISSUE TITLE
Import probblem?

### ISSUE THREAD

**Issue by Gliba** [zietbukuel/oktober-foundation#3]
I just tryed starter theme and i get this error

Uncaught SyntaxError: Unexpected token import
libraries.js:3860 jQuery.Deferred exception: $(...).foundation is not a function TypeError: $(...).foundation is not a function
    at HTMLDocument.<anonymous> (http://academlink.dev/themes/academlink/assets/js/theme.js:2:15)
    at mightThrow (http://academlink.dev/themes/academlink/assets/js/libraries.js:3583:29)
    at process (http://academlink.dev/themes/academlink/assets/js/libraries.js:3651:12) undefined
jQuery.Deferred.exceptionHook @ libraries.js:3860
process @ libraries.js:3655
libraries.js:3869 Uncaught TypeError: $(...).foundation is not a function
    at HTMLDocument.<anonymous> (theme.js:2)
    at mightThrow (libraries.js:3583)
    at process (libraries.js:3651)

**Comment by zietbukuel** [comment]
Could you please details the steps you did to replicate this same error? It seems to me that you didn't properly build the assets, but I can't say for sure because I need some more information.

**Comment by Gliba** [comment]
Install with artisan command and just run gulp, is there anything else?  I follow the docs... F6.4 was relished 5 days ago, maybe something different?

**Comment by Gliba** [comment]
Ok, after clearing npm modules and instaling again no errors.

**Comment by Gliba** [comment]
Ok, its problem with new version of fondation 6.4.1. Fondation 6.3.* working

**Comment by zietbukuel** [comment]
Yes, this theme supports 6.3.* only, I'll update it as soon as I can to work with the latest version.
