### ISSUE TITLE
Gulp watch catches first file change then hangs

### ISSUE THREAD

**Issue by douglasgough** [zietbukuel/oktober-foundation#4]
When I run 'gulp watch' or 'yarn run watch' I see this output:

`[01:44:50] Using gulpfile ~/workspace/install-master/themes/zietbukuel-oktober-foundation/gulpfile.js
[01:44:50] Starting 'watch'...
[01:44:50] Finished 'watch' after 21 ms`

When I make a change to a watched scss file I don't see any command line output telling me that it's compiled the changes, and there is no change to the website styles when I refresh the browser.

**Comment by douglasgough** [comment]
Sometimes I get `[01:56:31] Starting 'styles'...` when I make a change, but it's unpredictable. If it does make it to `[01:56:31] Starting 'styles'...` it hangs after that and doesn't detect or compile any more changes.

**Comment by zietbukuel** [comment]
I'm sorry for the huge delay, but I'm unable to reproduce this bug. Soon, I will be updating the theme to use the latest version of Foundation. Maybe things will change.
